export { About } from "./about";
export { Blog } from "./blog";
export { MainPage } from "./index.jsx";
export { Favorite } from "./favorite";
export { Card } from "./card";
export { Profile } from "./profile";
export { Cart } from "./cart";
export { Catalog } from "./catalog";
export { Complete } from "./complete";
